### ISSUE TITLE
Can't to load dependency 

### ISSUE THREAD

**Issue by VitalyPeryatin** [vipulasri/kachetor#1]
<img width="1232" alt="image" src="https://github.com/user-attachments/assets/6d78a534-04e8-4046-af56-c0015a4286d4">

I have `mavenCentral()` as repository for dependencies
<img width="510" alt="image" src="https://github.com/user-attachments/assets/0d36360b-08f8-4849-8ca8-7721f2839a98">

**Comment by vipulasri** [comment]
Hey @VitalyPeryatin,

Please verify that you are importing the library as: `com.vipulasri.kachetor:kachetor:<version>`.

The screenshot you shared above shows the error on `com.github.kachetor` but the import should be `com.vipulasri.kachetor`

**Comment by VitalyPeryatin** [comment]
Oh my god
I haven't checked code by AI Assistant. Thanks a lot!
